INSERT INTO TipusSolucions values ('Sitio web')
INSERT INTO TipusSolucions values ('Comercio electrónico')
INSERT INTO TipusSolucions values ('Gestión de redes sociales')
INSERT INTO TipusSolucions values ('Gestión de clientes')
INSERT INTO TipusSolucions values ('Business Inteligence')
INSERT INTO TipusSolucions values ('Gestion de Procesos')
INSERT INTO TipusSolucions values ('Factura electrónica')
INSERT INTO TipusSolucions values ('Oficina virtual')
INSERT INTO TipusSolucions values ('Comunicaciones seguras')
INSERT INTO TipusSolucions values ('Ciberseguridad')